### ISSUE TITLE
Cards not rendering straight

### ISSUE THREAD

**Issue by sturrock** [webraptor/react-native-deck-swiper#31]
When the Swiper renders the cards they are coming out weird, sometimes it works but most the time it doesn't. You cant swipe it either.

I noticed it does it when you open the app, then once you refresh the app with Ctrl+R it fixes itself. Its rendering the first card as the swipeBackCard then its rendering the other cards with rotation, and out of order indexes. 

Any ideas whats going on and is there a fix?

<img width="418" alt="94981805-8cb7c400-0578-11eb-9b78-984cbc8fc138" src="https://user-images.githubusercontent.com/33506226/95043681-350c8a80-0729-11eb-9430-994428768832.png">

**Comment by webraptor** [comment]
[Duplicate](https://github.com/webraptor/react-native-deck-swiper/issues/30)

**Comment by sturrock** [comment]
This is a different error, I figured out how to fix it. 

In Swiper.js you need to change line 8 from ```const { height, width } = Dimensions.get('window')``` to ```const { height, width } = Dimensions.get('screen')```

**Comment by webraptor** [comment]
> This is a different error, I figured out how to fix it.
> 
> In Swiper.js you need to change line 8 from `const { height, width } = Dimensions.get('window')` to `const { height, width } = Dimensions.get('screen')`

If you’ve got it solved in a fork please submit a PR. Thanks!

**Comment by webraptor** [comment]
The change would also impact only Androids. 

https://stackoverflow.com/questions/44978804/whats-the-difference-between-window-and-screen-in-the-dimensions-api/44979327

**Comment by ali14N** [comment]
changed line 8 still getting tilt card. anyone found any solution?

**Comment by webraptor** [comment]
The issue is likely from the pan responder not the width / height of the the deck of cards.

**Comment by Fazatholomew** [comment]
Same problem here. The card will be misplaced after the first swipe. Below is the props:
<Swiper
              ref={swiperRef}
              cards={data}
              cardIndex={index}
              renderCard={(card) => (
                <Card
                  card={card}
                  handleClick={() => handleClick(data[index])}
                />
              )}
              infinite
              keyExtractor={(card) => `${card.ticker} ${Date.now()}`}
              backgroundColor={'transparent'}
              onSwiped={onSwiped}
              onSwipedRight={() => handleClick(data[index])}
              onSwipedLeft={() => handleReject(data[index])}
              onTapCard={() => swiperRef.current.swipeLeft()}
              cardVerticalMargin={50}
              stackSize={stackSize}
              stackScale={10}
              stackSeparation={14}
              disableTopSwipe
              disableBottomSwipe
            />
![IMG_910E3AF50545-1](https://user-images.githubusercontent.com/22117863/103035508-74cb5d00-4535-11eb-94d9-872f1ee6ebd7.jpeg)

**Comment by webraptor** [comment]
Fixed on 2.0.11
